spring:
  application:
    name: exam_solbeg
  sql:
    init:
      mode: embedded
  datasource:
#    url: jdbc:sqlserver://127.0.0.1:6661;databaseName=test
    url: jdbc:postgresql://localhost:5432/solbeg
    username: solbeg
    password: solbeg
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
#    database: sql_server
    database: postgresql
    open-in-view: false
    defer-datasource-initialization: true
  jackson:
    default-property-inclusion: always
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  flyway:
    enabled: false

server:
  port: 8888

springdoc:
  swagger-ui:
    enabled: true

custom:
  jwt:
    tag: Solbeg
    secret: 05a789d4563f76cb1870c48c7208090105a789d4563f76cb1870c48c7208090105a789d4563f76cb1870c48c72080901
    expirationTime: 3600000 #1 hour
  csv:
    tags:
      create: false
      file-name: data-tags.csv
      count: 25
    authors:
      create: false
      file-name: data-authors.csv
      count: 150
    books:
      create: false
      file-name: data-books.csv
      count: 5000
